### ISSUE TITLE
ROSE_geneMapper.py output files related question

### ISSUE THREAD

**Issue by sylestiel** [younglab/ROSE#3]
Hi @abraham2, @chlazaris,

I ran into the IndexError:list index out of range at ROSE_geneMapper.py step.
I tried to address it by manually removing all chr*_ nomenclature from mm10_AllStitched.table.txt. (https://github.com/stjude/ROSE/issues/24)
However, I do not know what to expect in terms of output files at the end of this step.
<img width="418" alt="Screenshot 2024-05-15 at 1 41 51 PM" src="https://github.com/younglab/ROSE/assets/64283689/07dd05bb-e699-4d98-a6a4-ce0f1656eb60">
There are the files in my output folder.

Can you explain/list the output files from running this command.
 ROSE_geneMapper.py -g mm10 -i /FILEPATH/ROSE/bin/output/mm10_SuperStitched.table.txt -r TRUE -c
ROSE_geneMapper.py -g mm10 -i /FILEPATH/ROSE/bin/output/mm10_AllStitched.table.txt -r TRUE -c

Traceback (most recent call last):
  File "/PATH/ROSE/bin/ROSE_geneMapper.py", line 298, in <module>
    main()
  File "/PATH/ROSE/bin/ROSE_geneMapper.py", line 281, in main
    enhancerToGeneTable,geneToEnhancerTable,withGenesTable = mapEnhancerToGene(annotFile,enhancerFile, uniqueGenes=True, byRefseq=options.refseq, subtractInput=options.control, transcribedFile=transcribedFile)
  File "/PATH/ROSE/bin/ROSE_geneMapper.py", line 140, in mapEnhancerToGene
    closestGene = allEnhancerGenes[distList.index(min(distList))]
IndexError: list index out of range

Error still persists!

Many thanks!

**Comment by Portulaca666** [comment]
So what is the  solution?

**Comment by erzakiev** [comment]
why closing the question without posting a solution

**Comment by sylestiel** [comment]
Hi @Portulaca666 @erzakiev 
I believe I encountered this problem because I did not set the PATH environment variable correctly as outlined here https://github.com/stjude/ROSE#changes-from-source
PATHTO=/path/to/ROSE
PYTHONPATH=$PATHTO/lib
export PYTHONPATH
export PATH=$PATH:$PATHTO/bin

Having addressed that it worked.

**Comment by erzakiev** [comment]
@sylestiel hello, thank you, but it still throws the same error
